name: Run Unit Tests

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  run-tests:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Xcode select
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.4
      - name: Run tests
        run: xcodebuild test -project CI-Test-Project.xcodeproj -scheme CI-Test-Project -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'